# Generated by Django 4.2.3 on 2023-07-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singup',
            new_name='Signup',
        ),
    ]
