# Generated by Django 4.2.3 on 2023-07-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0002_rename_singup_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='profile/'),
        ),
    ]
