# Generated by Django 4.2.3 on 2023-07-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0006_alter_signup_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='usertype',
            field=models.CharField(default='buyer', max_length=100),
        ),
    ]
