# Generated by Django 4.2.3 on 2023-07-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0007_signup_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='usertype',
            field=models.CharField(default='Patient', max_length=100),
        ),
    ]
