# Generated by Django 4.2.3 on 2023-08-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0010_alter_appointment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
