# Generated by Django 4.2.4 on 2024-01-03 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_doctors', '0015_alter_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usertype',
        ),
    ]
